###############################################################################
#
#  Copyright 2026 OVITO GmbH, Germany
#
###############################################################################

# This file is only included when BUILD_TESTING and OVITO_BUILD_CPP_TESTS are ON.
ADD_SUBDIRECTORY(cpp)
