////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2026 OVITO GmbH, Germany
//
//  This file is part of OVITO (Open Visualization Tool).
//
//  OVITO is free software; you can redistribute it and/or modify it either under the
//  terms of the GNU General Public License version 3 as published by the Free Software
//  Foundation (the "GPL") or, at your option, under the terms of the MIT License.
//  If you do not alter this notice, a recipient may use your version of this
//  file under either the GPL or the MIT License.
//
//  You should have received a copy of the GPL along with this program in a
//  file LICENSE.GPL.txt.  You should have received a copy of the MIT License along
//  with this program in a file LICENSE.MIT.txt
//
//  This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND,
//  either express or implied. See the GPL or the MIT License for the specific language
//  governing rights and limitations.
//
////////////////////////////////////////////////////////////////////////////////////////

#pragma once


#include <ovito/stdmod/StdMod.h>
#include <ovito/stdmod/modifiers/ColorCodingModifier.h>
#include <ovito/stdobj/properties/PropertyColorMapping.h>
#include <ovito/stdobj/properties/ElementTypeSymbol.h>
#include <ovito/core/viewport/overlays/ViewportOverlay.h>
#include <ovito/core/rendering/FrameBuffer.h>
#include <ovito/core/rendering/SceneRenderer.h>

namespace Ovito {

/**
 * \brief A viewport overlay that displays the color legend of a ColorCodingModifier.
 */
class OVITO_STDMOD_EXPORT ColorLegendOverlay : public ViewportOverlay
{
    OVITO_CLASS(ColorLegendOverlay)

public:

    /// Custom notification event types generated by this class:
    enum {
        /// Notification event that is generated whenever the automatic label texts got recalculated during rendering.
        AutoLabelsUpdated = ViewportOverlay::NEXT_AVAILABLE_EVENT_ID,

        /// End-of-list value indicating the next available event type that can be used by sub-classes for custom notifications.
        NEXT_AVAILABLE_EVENT_ID
    };

    /// This virtual method gets called when the overlay is being newly attached to a viewport.
    virtual void initializeOverlay(Viewport* viewport) override;

    /// Lets the overlay paint its contents into the framebuffer (asynchronous coroutine; may evaluate a data pipeline).
    virtual Future<PipelineStatus> renderAsynchronous(OORef<FrameGraph> frameGraph, FrameGraph::RenderingCommandGroup& commandGroup, QRect logicalViewportRect, QRect physicalViewportRect, ViewProjectionParameters noninteractiveProjParams, OORef<const Scene> scene) override;

    /// Moves the position of the overlay in the viewport by the given amount,
    /// which is specified as a fraction of the viewport render size.
    virtual void moveLayerInViewport(const Vector2& delta) override {
        auto roundPercent = [](FloatType f) { return std::round(f * 1e4) / 1e4; };
        setOffsetX(roundPercent(offsetX() + delta.x()));
        setOffsetY(roundPercent(offsetY() + delta.y()));
    }

    /// Returns a short piece of information (typically a string or color) to be displayed next to the object's title in the pipeline editor.
    virtual QVariant getPipelineEditorShortInfo(Scene* scene) const override;

protected:

    /// Is called when the value of a property of this object has changed.
    virtual void propertyChanged(const PropertyFieldDescriptor* field) override;

    /// Is called when a RefTarget referenced by this object generated an event.
    virtual bool referenceEvent(RefTarget* source, const ReferenceEvent& event) override;

    /// Is called when the value of a reference field of this object changes.
    virtual void referenceReplaced(const PropertyFieldDescriptor* field, RefTarget* oldTarget, RefTarget* newTarget, int listIndex) override;

    /// This method is called once for this object after they have been completely loaded from a stream.
    virtual void loadFromStreamComplete(ObjectLoadStream& stream) override;

private:

    /// Computes the position and size of the color bar rectangle within the viewport, in physical device pixels.
    [[nodiscard]] QRectF computeColorBarRect(const QRect& physicalViewportRect, FloatType legendSize, FloatType aspectRatio) const;

    /// Draws the color legend for a Color Coding modifier.
    void drawContinuousColorMap(FrameGraph& frameGraph, FrameGraph::RenderingCommandGroup& commandGroup, const QRectF& colorBarRect,
                                FloatType legendSize, const PseudoColorMapping& mapping);

    /// Compiles the list of typed properties in a pipeline output which can serve as source for a discrete color legend.
    /// The returned paths are ordered by decreasing relevance: the typed properties of an outer data container,
    /// e.g. the particle types, precede those of its nested sub-containers, e.g. the bond, angle, dihedral, and
    /// improper types of a molecular dataset.
    [[nodiscard]] static std::vector<ConstDataObjectPath> listTypedProperties(const PipelineFlowState& state);

    using DiscreteColorMapLabels = std::vector<std::tuple<int, QString, Color>>;
    /// Returns the enabled element types of a typed property, sorted by numeric ID. Types that are
    /// indistinguishable in the legend, i.e., which have the same name, color, and 3d shape, are reported only once.
    [[nodiscard]] static std::vector<const ElementType*> getSortedElementTypes(const Property* property, const DataVis* visElement);
    /// Converts a typed property into an array to be used as input for drawDiscreteColorMap
    [[nodiscard]] static DiscreteColorMapLabels getDiscreteColorMapLabels(const Property* property, const DataVis* visElement);
    /// Converts a given number of discrete colors into an array to be used as input for drawDiscreteColorMap
    [[nodiscard]] DiscreteColorMapLabels getDiscreteColorMapLabels(const ColorCodingGradient* gradient, FloatType startValue,
                                                                   FloatType endValue, int orientation) const;

    /// Queries the 3d shapes representing the element types of a typed property. Returns an empty array if not a
    /// single one of the types provides a 3d representation, in which case flat color boxes should be drawn instead.
    [[nodiscard]] static std::vector<ElementTypeSymbol> getTypeSymbols(const Property* property, const DataVis* visElement);

    /// Returns the renderer to be used for rendering the 3d type symbols. It is a fresh instance of the same class
    /// as the renderer that is going to execute the current frame graph, configured with standardized settings.
    [[nodiscard]] SceneRenderer* acquireSymbolRenderer(const OORef<SceneRenderer>& frameGraphRenderer);

    /// Renders the 3d shapes of the given element types into a single offscreen image. The shapes are laid out in a
    /// row (horizontal) or column (vertical) of square cells sharing one orthographic camera, so that their relative
    /// sizes are preserved. Must be called from the main thread while a task context with a user interface is active.
    /// The returned image is in QImage::Format_RGBA8888 with straight (non-premultiplied) alpha.
    [[nodiscard]] Future<QImage> renderTypeSymbolImage(std::vector<ElementTypeSymbol> symbols, QSize imageSize, int orientation,
                                                        OORef<SceneRenderer> renderer);

    /// Returns the cached offscreen image showing the 3d shapes of the given element types, rendering it if necessary.
    [[nodiscard]] SharedFuture<QImage> lookupOrRenderTypeSymbolImage(std::vector<ElementTypeSymbol> symbols, QSize imageSize,
                                                                     int orientation, SceneRenderer* renderer);

    /// Discards all cached type symbol images and the renderer used for producing them.
    void invalidateSymbolImageCache();

    /// Draws the color legend for a typed property.
    /// If a non-null symbol image is provided, it is composited into the color bar in place of the flat color boxes.
    void drawDiscreteColorMap(FrameGraph& frameGraph, FrameGraph::RenderingCommandGroup& commandGroup, const QRectF& colorBarRect,
                              FloatType legendSize, const DiscreteColorMapLabels& colorMapLabels, const QImage& symbolImage = {});

    // Determine the starting value and the tick spacing for a given color bar length and character size
    [[nodiscard]] std::tuple<FloatType, FloatType> getAutomaticTickPositions(FloatType lowerLimit, FloatType upperLimit,
                                                                             const FloatType lenColorbar, const QFontMetricsF& fontMetrics,
                                                                             const QByteArray& labelFormat, const int maxIter = 50) const;

    // Determine the starting value for a given tick spacing.
    [[nodiscard]] static FloatType getUserDefinedTickPositions(FloatType lowerLimit, FloatType upperLimit, const FloatType inter);

    /// The corner of the viewport where the color legend is displayed.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(int{Qt::AlignHCenter | Qt::AlignBottom}, alignment, setAlignment, PROPERTY_FIELD_MEMORIZE);

    /// The orientation (horizontal/vertical) of the color legend.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(int{Qt::Horizontal}, orientation, setOrientation, PROPERTY_FIELD_MEMORIZE);

    /// Controls the overall size of the color legend.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(FloatType{0.3}, legendSize, setLegendSize, PROPERTY_FIELD_MEMORIZE);

    /// Controls the aspect ration of the color bar.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(FloatType{8.0}, aspectRatio, setAspectRatio, PROPERTY_FIELD_MEMORIZE);

    /// Controls the horizontal offset of legend position.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(FloatType{0}, offsetX, setOffsetX)

    /// Controls the vertical offset of legend position.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(FloatType{0}, offsetY, setOffsetY);

    /// Controls the title and label font.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(QFont{}, font, setFont, PROPERTY_FIELD_MEMORIZE);

    /// Controls the title font size.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(FloatType{0.1}, fontSize, setFontSize, PROPERTY_FIELD_MEMORIZE);

    /// Controls the relative (as fraction of the title font size) label font size.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(FloatType{0.6}, relLabelFontSize, setRelLabelFontSize, PROPERTY_FIELD_MEMORIZE);

    /// User-defined text for the caption of the color legend. If empty, an automatically
    /// generated caption is displayed instead.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{}, caption, setCaption);

    /// User-defined text for the first numeric label. If empty, an automatically generated label is displayed instead.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{}, label1, setLabel1);

    /// User-defined text for the second numeric label. If empty, an automatically generated label is displayed instead.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{}, label2, setLabel2);

    /// The ColorCodingModifier for which to display the legend.
    DECLARE_MODIFIABLE_REFERENCE_FIELD_FLAGS(OORef<ColorCodingModifier>, modifier, setModifier,
                                             PROPERTY_FIELD_NEVER_CLONE_TARGET | PROPERTY_FIELD_NO_SUB_ANIM |
                                                 PROPERTY_FIELD_DONT_PROPAGATE_MESSAGES);

    /// The selected PropertyColorMapping for which to display the legend.
    DECLARE_MODIFIABLE_REFERENCE_FIELD_FLAGS(OORef<PropertyColorMapping>, colorMapping, setColorMapping,
                                             PROPERTY_FIELD_NEVER_CLONE_TARGET | PROPERTY_FIELD_NO_SUB_ANIM |
                                                 PROPERTY_FIELD_DONT_PROPAGATE_MESSAGES);

    /// Controls the formatting of the value labels in the color legend.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{QStringLiteral("%g")}, valueFormatString, setValueFormatString);

    /// Controls the text color.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS((Color{0, 0, 0}), textColor, setTextColor, PROPERTY_FIELD_MEMORIZE);

    /// The text outline color.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS((Color{1, 1, 1}), outlineColor, setOutlineColor, PROPERTY_FIELD_MEMORIZE);

    /// Controls the outlining of the font.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{false}, outlineEnabled, setOutlineEnabled, PROPERTY_FIELD_MEMORIZE);

    /// The typed property whose element types are shown by the legend.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(PropertyDataObjectReference{}, sourceProperty, setSourceProperty);

    /// Controls the display of the actual 3d shapes of the element types instead of flat color boxes.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{true}, useTypeShapes, setUseTypeShapes, PROPERTY_FIELD_MEMORIZE);

    /// Controls the drawing of a border around the color map.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{false}, borderEnabled, setBorderEnabled, PROPERTY_FIELD_MEMORIZE);

    /// The border color.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS((Color{0, 0, 0}), borderColor, setBorderColor, PROPERTY_FIELD_MEMORIZE);

    // Toggle tick marks.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{false}, ticksEnabled, setTicksEnabled, PROPERTY_FIELD_MEMORIZE);

    // Controls the manual tick spacing.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(FloatType{0}, tickSpacing, setTickSpacing);

    // Controls the rotation of the caption.
    // For vertical color bars the caption can either be vertical (enabled=true) or horizontal (enabled=false).
    // This flag has no effect for horizontal color bars.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{false}, titleRotationEnabled, setTitleRotationEnabled, PROPERTY_FIELD_MEMORIZE);

    // Toggle background.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS(bool{false}, backgroundEnabled, setBackgroundEnabled, PROPERTY_FIELD_MEMORIZE);

    // Background color.
    DECLARE_MODIFIABLE_PROPERTY_FIELD_FLAGS((Color{1, 1, 1}), backgroundColor, setBackgroundColor, PROPERTY_FIELD_MEMORIZE);

    /// The automatically chosen texts of the caption and numeric labels. These strings are determined during rendering of the overlay and
    /// will subsequently be displayed in the GUI panel as placeholder texts in the input fields.
    QString _autoTitleText, _autoLabel1Text, _autoLabel2Text;

    /// A cached offscreen rendering of the 3d shapes of the element types.
    struct SymbolImageCacheEntry {
        /// The element type shapes the image was rendered for.
        std::vector<ElementTypeSymbol> symbols;
        /// The size of the image in physical device pixels.
        QSize imageSize;
        /// The layout direction of the symbol cells.
        int orientation;
        /// The class of the renderer the image was produced with.
        OvitoClassPtr rendererClass;
        /// The rendered image. Note that the rendering operation may still be in flight.
        SharedFuture<QImage> image;
    };

    /// Cache of rendered symbol images, most recently used first. It is bounded to a few entries, so that several
    /// viewports of different sizes showing the same legend do not evict each other's images.
    std::deque<SymbolImageCacheEntry> _symbolImageCache;

    /// The renderer used for producing the type symbol images. It is lazily created from the class of the renderer
    /// that is going to execute the frame graph. Never serialized.
    OORef<SceneRenderer> _symbolRenderer;

    /// The class of the frame graph's renderer from which _symbolRenderer was derived. Note that this is not
    /// necessarily the class of _symbolRenderer itself, because a renderer may decline to render preview images.
    OvitoClassPtr _symbolRendererSourceClass = nullptr;

    /// Is set once offscreen rendering has turned out to be unavailable, to avoid retrying it for every frame.
    bool _symbolRenderingUnavailable = false;

    friend class ColorLegendOverlayEditor;
};

}   // End of namespace
