###############################################################################
#
#  Copyright 2026 OVITO GmbH, Germany
#
###############################################################################

ADD_SUBDIRECTORY(core/automation)
ADD_SUBDIRECTORY(core/math)
ADD_SUBDIRECTORY(core/utilities)
ADD_SUBDIRECTORY(stdobj/simcell)
