////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2026 OVITO GmbH, Germany
//
//  This file is part of OVITO (Open Visualization Tool).
//
//  OVITO is free software; you can redistribute it and/or modify it either under the
//  terms of the GNU General Public License version 3 as published by the Free Software
//  Foundation (the "GPL") or, at your option, under the terms of the MIT License.
//  If you do not alter this notice, a recipient may use your version of this
//  file under either the GPL or the MIT License.
//
//  You should have received a copy of the GPL along with this program in a
//  file LICENSE.GPL.txt.  You should have received a copy of the MIT License along
//  with this program in a file LICENSE.MIT.txt
//
//  This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND,
//  either express or implied. See the GPL or the MIT License for the specific language
//  governing rights and limitations.
//
////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <ovito/stdmod/StdMod.h>
#include <ovito/stdobj/properties/GenericPropertyModifier.h>
#include <ovito/stdobj/properties/PropertyReference.h>
#include <ovito/stdobj/textlabels/TextLabelsVis.h>
#include <ovito/core/dataset/pipeline/ModificationNode.h>

namespace Ovito {

/**
 * \brief Turns the values of a property into text labels, which are displayed next to the data elements.
 *
 * The modifier generates a new string property holding the label texts and attaches its own TextLabelsVis
 * element to it. All conversion of property values into strings happens here, not in the visual element.
 */
class OVITO_STDMOD_EXPORT TextLabelsModifier : public GenericPropertyModifier
{
    OVITO_CLASS(TextLabelsModifier)

public:
    /// Constructor.
    void initializeObject(ObjectInitializationFlags flags);

    /// This method is called by the system after the modifier has been inserted into a data pipeline.
    virtual void initializeModifier(const ModifierInitializationRequest& request) override;

    /// Modifies the input data.
    virtual Future<PipelineFlowState> evaluateModifier(const ModifierEvaluationRequest& request, PipelineFlowState&& state) override;

    /// Asks the modifier to replace a visual element owned by this modifier with a new compatible object, which is created
    /// on demand by the provided callback function.
    virtual void replaceVisualElement(DataVis* visElement, const std::function<OORef<DataVis>(const QString&)>& getReplacement) override;

    /// Returns a short piece of information to be displayed next to the modifier's title in the pipeline editor list.
    virtual QVariant getPipelineEditorShortInfo(Scene* scene, ModificationNode* node) const override
    {
        // Note: Whenever the source property changes, we trigger a ReferenceEvent::ObjectStatusChanged event in propertyChanged().
        return sourceProperty().nameWithComponent();
    }

    /// The default name given to the string property generated by the modifier.
    [[nodiscard]] static QString defaultOutputPropertyName() { return QStringLiteral("Text Label"); }

    /// Indicates whether the given property can serve as the source of the labels' anchor positions.
    [[nodiscard]] static bool isValidPositionProperty(const Property* property)
    {
        return property->componentCount() == 3 && property->dataType() == Property::FloatDefault;
    }

    /// One conversion specifier of the format string together with the literal text preceding it.
    struct FormatSpecifier
    {
        QString literal;            ///< The literal text before the specifier, with '%%' already unescaped.
        QByteArray specifier;       ///< The normalized specifier itself, e.g. "%.2f" or "%lld".
        bool isInteger{};           ///< Whether the value must be handed to asprintf() as a 'long long'.
    };

    /// A printf-style format string broken down into its conversion specifiers and literal parts.
    struct ParsedFormatString
    {
        std::vector<FormatSpecifier> specifiers;    ///< One entry per conversion specifier, in order of appearance.
        QString trailingLiteral;                    ///< The literal text following the last specifier, '%%' unescaped.
    };

    /// Breaks a printf-style format string down into its conversion specifiers and literal parts.
    /// Returns false and an error message if the string cannot be used to format property values.
    [[nodiscard]] static bool parseFormatString(const QString& format, ParsedFormatString& result, QString& errorMessage);

protected:
    /// Is called when the value of a property of this object has changed.
    virtual void propertyChanged(const PropertyFieldDescriptor* field) override;

private:
    /// Picks a property of the given input container to serve as the labels' anchor positions.
    /// Does nothing unless the container is a data table, which has no intrinsic positions.
    /// An existing selection is kept as long as it still refers to a usable property of the container.
    void autodetectPositionProperty(const PropertyContainer* container);

    /// Converts the values of the given input property into the label strings.
    static void generateLabelStrings(const Property* inputProperty, int vectorComponent, const ParsedFormatString& format, const Property* selection, Property* labels);

private:
    /// The input property whose values are turned into text labels.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(PropertyReference{}, sourceProperty, setSourceProperty);

    /// The property providing the 3d coordinates at which the labels are placed.
    /// This parameter is used only for input containers that have no intrinsic anchor positions,
    /// i.e. data tables, and is ignored for all other kinds of data elements.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(PropertyReference{}, positionProperty, setPositionProperty);

    /// The name of the string property generated by this modifier. Not user-configurable: the name is
    /// assigned automatically when the modifier is inserted into a pipeline (see initializeModifier()),
    /// and is stored here only to keep it stable across pipeline re-evaluations.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{QStringLiteral("Text Label")}, outputProperty, setOutputProperty);

    /// Controls the formatting of the property values. Literal text in this string, e.g. a unit symbol,
    /// is incorporated into every label.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(QString{QStringLiteral("%g")}, valueFormatString, setValueFormatString);

    /// Controls whether labels are generated only for the currently selected elements.
    DECLARE_MODIFIABLE_PROPERTY_FIELD(bool{false}, onlySelected, setOnlySelected);

    /// The vis element for rendering the text labels.
    DECLARE_MODIFIABLE_REFERENCE_FIELD_FLAGS(OORef<TextLabelsVis>,
                                             textLabelsVis,
                                             setTextLabelsVis,
                                             PROPERTY_FIELD_DONT_PROPAGATE_MESSAGES | PROPERTY_FIELD_MEMORIZE |
                                                 PROPERTY_FIELD_OPEN_SUBEDITOR);
};

}  // namespace Ovito
