// SPDX-FileCopyrightText: 2026 OVITO GmbH, Germany
// SPDX-License-Identifier: GPL-3.0-only OR MIT

#include <ovito/stdmod/StdMod.h>
#include <ovito/core/dataset/DataSet.h>
#include <ovito/core/dataset/pipeline/ModificationNode.h>
#include <ovito/core/dataset/DataSetContainer.h>
#include <ovito/core/app/UserInterface.h>
#include <ovito/stdobj/properties/Property.h>
#include <ovito/stdobj/properties/ElementType.h>
#include <ovito/stdobj/properties/PropertyContainer.h>
#include <ovito/stdobj/table/DataTable.h>
#include "TextLabelsModifier.h"

namespace Ovito {

IMPLEMENT_CREATABLE_OVITO_CLASS(TextLabelsModifier);
OVITO_CLASSINFO(TextLabelsModifier, "DisplayName", "Add text labels");
OVITO_CLASSINFO(TextLabelsModifier, "Description", "Display the values of a property as text labels next to the data elements.");
OVITO_CLASSINFO(TextLabelsModifier, "ModifierCategory", "Visualization");
DEFINE_PROPERTY_FIELD(TextLabelsModifier, sourceProperty);
DEFINE_PROPERTY_FIELD(TextLabelsModifier, positionProperty);
DEFINE_PROPERTY_FIELD(TextLabelsModifier, outputProperty);
DEFINE_PROPERTY_FIELD(TextLabelsModifier, valueFormatString);
DEFINE_PROPERTY_FIELD(TextLabelsModifier, onlySelected);
DEFINE_REFERENCE_FIELD(TextLabelsModifier, textLabelsVis);
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, sourceProperty, "Property");
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, positionProperty, "Position property");
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, outputProperty, "Output property");
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, valueFormatString, "Format");
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, onlySelected, "Label only selected elements");
SET_PROPERTY_FIELD_LABEL(TextLabelsModifier, textLabelsVis, "Text labels");

/******************************************************************************
* Constructor.
******************************************************************************/
void TextLabelsModifier::initializeObject(ObjectInitializationFlags flags)
{
    GenericPropertyModifier::initializeObject(flags);

    // Operate on particles by default.
    setDefaultSubject(QStringLiteral("Particles"), QStringLiteral("Particles"));

    if(!flags.testFlag(ObjectInitializationFlag::DontInitializeObject)) {
        // Create the vis element for rendering the labels generated by the modifier.
        setTextLabelsVis(OORef<TextLabelsVis>::create(flags));
        textLabelsVis()->setObjectTitle(tr("Text labels"));
    }
}

/******************************************************************************
* This method is called by the system when the modifier has been inserted
* into a pipeline.
******************************************************************************/
void TextLabelsModifier::initializeModifier(const ModifierInitializationRequest& request)
{
    GenericPropertyModifier::initializeModifier(request);

    if(!subject())
        return;

    const PipelineFlowState& input = request.modificationNode()->evaluateInput(request).blockForResult();
    const PropertyContainer* container = input.getLeafObject(subject());
    if(!container)
        return;

    // Note: No input property is preselected here. The modifier stays inactive until the
    // user picks one, because there is no way to guess which property makes meaningful labels.

    // A data table does not provide anchor positions of its own. Pick a property that could
    // serve as the labels' anchor points, leaving the final choice to the user.
    autodetectPositionProperty(container);

    // Give the generated property a name that is not already taken, so that several instances of the
    // modifier can be applied to the same container without overwriting each other's labels.
    // Note that the name is resolved once, at insertion time, to keep it stable when the user
    // subsequently enables or disables modifiers further up the pipeline.
    //
    // Note: The counter is appended with a space, not a dot. A dot separates a property name from a
    // vector component name ("Position.X"), so a name like "Text Label.2" could not be used to look
    // the generated property up again, neither from Python nor in an expression.
    QString name = defaultOutputPropertyName();
    for(int counter = 2; container->getProperty(name) != nullptr; counter++)
        name = QStringLiteral("%1 %2").arg(defaultOutputPropertyName()).arg(counter);
    setOutputProperty(std::move(name));
}

/******************************************************************************
* Picks a property of the given input container to serve as the labels' anchor positions.
******************************************************************************/
void TextLabelsModifier::autodetectPositionProperty(const PropertyContainer* container)
{
    // Only data tables need an explicitly designated position property.
    const DataTable* table = dynamic_object_cast<DataTable>(container);
    if(!table)
        return;

    // Keep the current selection if it still refers to a usable property of the input table.
    if(const Property* current = positionProperty().findInContainer(table); current && isValidPositionProperty(current))
        return;

    // Prefer the property the table itself has designated as its positions, e.g. because another
    // instance of this modifier is already labeling the same table.
    if(table->positions() && isValidPositionProperty(table->positions())) {
        setPositionProperty(table->positions());
        return;
    }

    // Otherwise fall back to the first property that could serve as anchor points.
    for(const Property* property : table->properties()) {
        if(isValidPositionProperty(property)) {
            setPositionProperty(property);
            return;
        }
    }

    // The table has nothing to offer. Discard a selection left over from a different input container,
    // so that the user is asked to make a new choice.
    setPositionProperty({});
}

/******************************************************************************
* Is called when the value of a property of this object has changed.
******************************************************************************/
void TextLabelsModifier::propertyChanged(const PropertyFieldDescriptor* field)
{
    if(field == PROPERTY_FIELD(TextLabelsModifier::sourceProperty) && !shouldIgnoreChanges()) {
        // Changes of this parameter affect the result of getPipelineEditorShortInfo().
        notifyDependents(ReferenceEvent::ObjectStatusChanged);
    }
    else if(field == PROPERTY_FIELD(GenericPropertyModifier::subject) && !shouldIgnoreChanges() && !isUndoingOrRedoing() && this_task::isInteractive()) {
        // The anchor positions are tied to the input container. When the user switches to a different one,
        // e.g. from particles to a data table, a matching position property must be picked again.
        if(subject()) {
            PipelineEvaluationRequest request(this_task::ui()->datasetContainer().currentAnimationTime());
            for(ModificationNode* node : nodes()) {
                try {
                    if(const PropertyContainer* container = node->evaluateInput(request).blockForResult().getLeafObject(subject()))
                        autodetectPositionProperty(container);
                }
                catch(...) {
                    // Ignore exceptions that occur during upstream pipeline evaluation.
                }
            }
        }
    }

    GenericPropertyModifier::propertyChanged(field);
}

/******************************************************************************
* Replaces any references the modifier has to the given visual element with a new compatible object.
******************************************************************************/
void TextLabelsModifier::replaceVisualElement(DataVis* visElement, const std::function<OORef<DataVis>(const QString&)>& getReplacement)
{
    if(textLabelsVis() == visElement)
        setTextLabelsVis(static_object_cast<TextLabelsVis>(getReplacement(tr("Text labels"))));
}

/******************************************************************************
* Modifies the input data.
******************************************************************************/
Future<PipelineFlowState> TextLabelsModifier::evaluateModifier(const ModifierEvaluationRequest& request, PipelineFlowState&& state)
{
    if(!subject())
        throw Exception(tr("No input element type selected."));
    if(!sourceProperty()) {
        // The modifier is in this state right after insertion, until the user picks an input property.
        state.setStatus(PipelineStatus(PipelineStatus::Warning, tr("Please select an input property.")));
        return std::move(state);
    }
    if(outputProperty().isEmpty())
        throw Exception(tr("Output property name must not be empty."));

    DataObjectPath objectPath = state.expectMutableObject(subject());
    PropertyContainer* container = static_object_cast<PropertyContainer>(objectPath.back());
    container->verifyIntegrity();

    if(!container->getOOMetaClass().supportsTextLabels()) {
        throw Exception(tr("Text labels are not supported for %1, because this kind of data element does not "
                           "provide anchor positions for the labels.").arg(container->getOOMetaClass().elementDescriptionName()));
    }

    // A data table has no standard position property. The column serving as anchor points for the labels
    // must be designated explicitly by the user. The choice is recorded in the output data table itself,
    // which is where the vis element picks it up at render time.
    // Note that all text label modifiers operating on the same table share this designation.
    if(DataTable* table = dynamic_object_cast<DataTable>(container)) {
        if(!positionProperty())
            throw Exception(tr("Please select the property of the data table that provides the 3d coordinates at which the labels are placed."));
        const Property* positions = positionProperty().findInContainer(table);
        if(!positions)
            throw Exception(tr("The property '%1' does not exist in the input data table.").arg(positionProperty().name()));
        if(positions->componentCount() != 3) {
            throw Exception(tr("The property '%1' cannot be used to position the labels, because it has %2 vector component(s). "
                               "Please select a property with 3 components.").arg(positions->name()).arg(positions->componentCount()));
        }
        if(positions->dataType() != Property::FloatDefault)
            throw Exception(tr("The property '%1' cannot be used to position the labels, because it does not store standard-precision floating-point values.").arg(positions->name()));
        table->setPositions(positions);
    }

    // Get the input property and resolve the referenced vector component (if any).
    // Note: Component resolution is not enforced here. A reference to a vector property as a whole
    // (vectorComponent == -1) is a valid selection, which turns all of its components into one label.
    QString errorDescription;
    auto [sourcePropertyObj, vectorComponent] = sourceProperty().findInContainerWithComponent(container, errorDescription, false);
    if(!sourcePropertyObj)
        throw Exception(std::move(errorDescription));
    if(sourcePropertyObj->dataType() == QMetaType::Void)
        throw Exception(tr("The input property '%1' has an unsupported data type.").arg(sourcePropertyObj->name()));
    if(sourcePropertyObj->dataType() == Property::String && sourcePropertyObj->componentCount() != 1)
        throw Exception(tr("The input property '%1' must be a scalar property.").arg(sourcePropertyObj->name()));
    ConstPropertyPtr inputProperty = sourcePropertyObj;

    // The number of values that go into each label.
    const int valueCount = (vectorComponent >= 0) ? 1 : (int)sourcePropertyObj->componentCount();

    // An empty format string is completed to one default conversion specifier per value.
    QString format = valueFormatString();
    if(format.isEmpty())
        format = QStringList(valueCount, QStringLiteral("%g")).join(QStringLiteral(", "));

    // Parse and validate the format string here, in the main thread, so that any problem with it
    // is reported to the user as an error status of the modifier.
    ParsedFormatString parsedFormat;
    if(!parseFormatString(format, parsedFormat, errorDescription))
        throw Exception(std::move(errorDescription));

    // A single conversion specifier is applied to every component of a vector property in turn.
    // This makes the default format string work for vector properties too, instead of forcing the
    // user to spell out one specifier per component before anything can be displayed.
    if(parsedFormat.specifiers.size() == 1 && valueCount > 1) {
        const FormatSpecifier prototype = parsedFormat.specifiers.front();
        for(int i = 1; i < valueCount; i++)
            parsedFormat.specifiers.push_back({.literal = QStringLiteral(", "), .specifier = prototype.specifier, .isInteger = prototype.isInteger});
    }

    // A format string without any conversion specifier produces a constant label text and is allowed
    // for any input property. Otherwise there must be exactly one specifier per value.
    if(!parsedFormat.specifiers.empty() && (int)parsedFormat.specifiers.size() != valueCount) {
        if(valueCount == 1) {
            throw Exception(tr("The format string contains %1 conversion specifiers, but the selected property provides "
                               "a single value per data element. Please use exactly one conversion specifier, e.g. \"%g\".")
                                .arg(parsedFormat.specifiers.size()));
        }
        else {
            throw Exception(tr("The format string contains %1 conversion specifiers, but the vector property '%2' has %3 components. "
                               "Please use one conversion specifier per component, e.g. \"%4\", or select an individual component "
                               "of the property.")
                                .arg(parsedFormat.specifiers.size())
                                .arg(sourcePropertyObj->name())
                                .arg(valueCount)
                                .arg(QStringList(valueCount, QStringLiteral("%g")).join(QStringLiteral(", "))));
        }
    }

    // Get the selection property if enabled by the user.
    ConstPropertyPtr selection;
    if(onlySelected() && container->getOOMetaClass().isValidStandardPropertyId(Property::GenericSelectionProperty))
        selection = container->getProperty(Property::GenericSelectionProperty);

    // Create the output property holding the label strings and attach the vis element to it.
    // Note: This must happen here, in the main thread, because the vis element is a reference field of
    // this modifier, which the GUI thread may concurrently replace while a worker task is running.
    Property* labels = container->createProperty(DataBuffer::Initialized, outputProperty(), Property::String);
    labels->setVisElement(textLabelsVis());

    // Tag the generated property with the pipeline node that created it. This lets the vis element
    // find its way back to this modifier when generating the short info for the pipeline editor.
    labels->setCreatedByNode(request.modificationNodeWeak());

    // The actual string conversion can be performed in a separate worker thread.
    // Note: 'labels' remains valid there, because the flow state owning it is moved into the task.
    return asyncLaunch([
            state = std::move(state),
            labels,
            inputProperty = std::move(inputProperty),
            vectorComponent,
            parsedFormat = std::move(parsedFormat),
            selection = std::move(selection)]() mutable
    {
        generateLabelStrings(inputProperty, vectorComponent, parsedFormat, selection, labels);

        return std::move(state);
    });
}

/******************************************************************************
* Breaks a printf-style format string down into its conversion specifiers and literal parts.
*
* Splitting the format string serves two purposes: It lets a single specifier be applied to each
* component of a vector property in turn, and it makes the literal parts of the string - a unit
* symbol, for example - available to property types that bring their own text representation and
* therefore never reach asprintf().
******************************************************************************/
bool TextLabelsModifier::parseFormatString(const QString& format, ParsedFormatString& result, QString& errorMessage)
{
    // The characters that may appear between the leading '%' and the conversion character.
    static const QString specifierBody = QStringLiteral("-+ #'0123456789.hlLqjzt");
    // The length modifiers among them, which are dropped during normalization.
    static const QString lengthModifiers = QStringLiteral("hlLqjzt");
    // The conversion characters that consume a floating-point resp. an integer argument.
    static const QString floatConversions = QStringLiteral("aAeEfFgG");
    static const QString intConversions = QStringLiteral("diouxX");

    // Unescapes the '%%' sequences of a printf format string.
    auto unescape = [](QStringView text) { return text.toString().replace(QStringLiteral("%%"), QStringLiteral("%")); };

    result.specifiers.clear();
    qsizetype literalStart = 0;
    for(qsizetype i = 0; i < format.size(); i++) {
        if(format[i] != QChar('%'))
            continue;
        if(i + 1 < format.size() && format[i + 1] == QChar('%')) {
            i++;  // An escaped percent sign, not the start of a conversion specifier.
            continue;
        }

        // Skip over the flags, field width, precision and length modifier to find the
        // conversion character, which terminates the specifier.
        qsizetype end = i + 1;
        while(end < format.size() && specifierBody.contains(format[end]))
            end++;
        if(end < format.size() && format[end] == QChar('*')) {
            errorMessage = tr("The conversion specifier '%1' in the format string uses a dynamic field width or precision ('*'), "
                              "which is not supported.").arg(format.mid(i, end - i + 1));
            return false;
        }
        if(end >= format.size()) {
            errorMessage = tr("The format string ends with an incomplete conversion specifier '%1'.").arg(format.mid(i));
            return false;
        }

        // Classify the conversion character to decide how the value must be passed to asprintf().
        const QChar conversion = format[end];
        const bool isInteger = intConversions.contains(conversion);
        if(!isInteger && !floatConversions.contains(conversion)) {
            errorMessage = tr("The conversion specifier '%1' in the format string cannot be used to format a numeric property value. "
                              "Please use one of the conversions %2 or %3.")
                               .arg(format.mid(i, end - i + 1))
                               .arg(QStringLiteral("%f, %e, %g"))
                               .arg(QStringLiteral("%d, %o, %x"));
            return false;
        }

        // Normalize the specifier: The length modifier written by the user is replaced by the one
        // matching the argument type this modifier is going to pass to asprintf().
        QString body = format.mid(i, end - i);
        while(!body.isEmpty() && lengthModifiers.contains(body.back()))
            body.chop(1);
        result.specifiers.push_back({
            .literal = unescape(format.mid(literalStart, i - literalStart)),
            .specifier = (body + (isInteger ? QStringLiteral("ll") : QString()) + conversion).toUtf8(),
            .isInteger = isInteger});

        i = end;
        literalStart = end + 1;
    }

    // Whatever follows the last specifier - or the entire string, if it contains no specifier at all -
    // becomes constant text appended to every label.
    result.trailingLiteral = unescape(format.mid(literalStart));
    return true;
}

/******************************************************************************
* Converts the values of the given input property into the label strings.
******************************************************************************/
void TextLabelsModifier::generateLabelStrings(const Property* inputProperty, int vectorComponent, const ParsedFormatString& format, const Property* selection, Property* labels)
{
    BufferWriteAccess<QString, access_mode::write> output(labels);
    BufferReadAccess<SelectionIntType> selectionAcc(selection);
    const size_t count = output.size();
    const size_t firstComponent = std::max(0, vectorComponent);

    // Assembles the label of the i-th element by interleaving the literal parts of the format string
    // with the text representations of the property's components.
    auto buildLabel = [&](size_t i, auto&& componentToText) {
        QString text;
        for(size_t k = 0; k < format.specifiers.size(); k++) {
            text += format.specifiers[k].literal;
            text += componentToText(i, firstComponent + k, format.specifiers[k]);
        }
        text += format.trailingLiteral;
        return text;
    };

    // Writes the i-th label, taking the selection state into account.
    // Note that unselected elements keep an empty label string, which TextLabelsVis skips.
    auto emitLabels = [&](auto&& componentToText) {
        for(size_t i = 0; i < count; i++) {
            if(selectionAcc && !selectionAcc[i])
                output[i] = QString();
            else
                output[i] = buildLabel(i, componentToText);
        }
    };

    if(inputProperty->dataType() == Property::Float32 || inputProperty->dataType() == Property::Float64) {
        // Floating-point values are the only ones that are formatted by asprintf() itself.
        RawBufferReadAccess input(inputProperty);
        emitLabels([&](size_t index, size_t component, const FormatSpecifier& spec) {
            const double value = input.get<double>(index, component);
            return spec.isInteger
                ? QString::asprintf(spec.specifier.constData(), (long long)value)
                : QString::asprintf(spec.specifier.constData(), value);
        });
    }
    else if(inputProperty->isTypedProperty() && vectorComponent <= 0) {
        // For typed properties, display the name of the element type instead of its numeric ID.
        BufferReadAccess<int32_t> input(inputProperty);
        emitLabels([&](size_t index, size_t component, const FormatSpecifier& spec) {
            const ElementType* type = inputProperty->elementType(input[index]);
            return type ? type->nameOrNumericId() : QString::number(input[index]);
        });
    }
    else if(inputProperty->dataType() == Property::String) {
        BufferReadAccess<QString> input(inputProperty);
        emitLabels([&](size_t index, size_t component, const FormatSpecifier& spec) { return input[index]; });
    }
    else {
        // An integer conversion is applied to an integer value as written by the user, so that a field
        // width, a zero padding or a hexadecimal conversion has the effect one would expect.
        //
        // A floating-point conversion, in contrast, is deliberately *not* applied: it would push large
        // identifiers into scientific notation and thereby destroy the exact value ("%g" turns 1234567
        // into "1.23457e+06"). Integers have an exact decimal representation of their own, which is used
        // instead - which is also what makes the default format string work for identifiers of any size.
        RawBufferReadAccess input(inputProperty);
        emitLabels([&](size_t index, size_t component, const FormatSpecifier& spec) {
            const qlonglong value = input.get<qlonglong>(index, component);
            return spec.isInteger ? QString::asprintf(spec.specifier.constData(), (long long)value) : QString::number(value);
        });
    }
}

}   // End of namespace
